# Generated by Django 3.0.5 on 2023-05-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canceledorders',
            name='customer',
        ),
        migrations.AddField(
            model_name='canceledorders',
            name='customerID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customerID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='model',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
