# Generated by Django 4.2 on 2023-05-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_car_car1_alter_car_car2_alter_car_car3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car1',
            field=models.ImageField(default='static/placeholder.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='car2',
            field=models.ImageField(default='static/placeholder.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='car3',
            field=models.ImageField(default='static/placeholder.png', null=True, upload_to=''),
        ),
    ]
